server:
  port: 8080
spring:
  application:
    name: club
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        connection:
          provider_disables_autocommit: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
application:
  jwt:
    token-expiration-second: ${SEC_TOKEN_EXP_DURATION:9000}
    secret-key: ${SEC_TOKEN_SECRET:myJWTSecretKey_2024!#%&()=+?@^_|~} #TODO: Change it
    authorization-header: Authorization
    token-prefix: Bearer
logging:
  level:
    root: info
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5p) %clr([%t]){magenta} %clr(%c{1.}:%L[%M]){cyan} - %m%n%wEx'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%t] %c{1.}:%L[%M] - %m%n%wEx'
  file:
    name: logs/app.log
