package com.snapp.snapppay.club.exception;

public interface ExceptionMessageCode {

    String PRINCIPAL_IS_NOT_VALID = "PRINCIPAL_IS_NOT_VALID";

    String USERNAME_IS_DUPLICATE = "USERNAME_IS_DUPLICATE";
    String NATIONAL_CODE_IS_DUPLICATE = "NATIONAL_CODE_IS_DUPLICATE";
    String PROVIDER_TITLE_IS_DUPLICATE = "PROVIDER_TITLE_IS_DUPLICATE";
    String THIS_USER_IS_ALREADY_A_PROVIDER = "THIS_USER_IS_ALREADY_A_PROVIDER";
}
